version: '3.8'

services:
  notebook:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ../src:/opt/src:cached
      - ..:/workspace:cached
    ports:
      - 8888:8888
